# Generated by Django 4.2.5 on 2023-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdetails',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
